class PerformanceConfig:
    MAX_FPS = 60
    MAX_PARTICLES = 50
    SPRITE_BATCH_SIZE = 100
    ENABLE_VSYNC = True
    PRELOAD_ASSETS = True
    SOUND_CHANNELS = 8
    MAX_ENEMIES = 50
    COLLISION_CHECK_FREQUENCY = 2  # frames
    BACKGROUND_SCROLL_OPTIMIZATION = True 